rvm:
  - 2.0.0
#  - 2.1.0
env:
  - PUPPET_VERSION="~> 3.6.0"
#  - PUPPET_VERSION="~> 3.7.0"
#  - PUPPET_VERSION="~> 3.8.0"
#  - PUPPET_VERSION="~> 4.0.0"
#  - PUPPET_VERSION="~> 4.1.0"
#  - PUPPET_VERSION="~> 4.2.0"
#  - PUPPET_VERSION="~> 4.3.0"
sudo: false
script:
  - "rake spec SPEC_OPTS='--format documentation'"
install:
  - bundle install
  - rspec-puppet-init
