version: 2

workflows:
  version: 2
  test:
    jobs:
      - lint
      - validate

jobs:
  lint:
    docker:
      - image: ruby:2.2.6
    steps:
      - checkout
      - run: bundle install
      - run: rake lint
  validate:
    docker:
      - image: ruby:2.2.6
    steps:
      - checkout
      - run: bundle install
      - run: rake validate
