version: 2.1

workflows:
  version: 2
  test:
    jobs:
      - validate
      - lint:
        requires:
          - validate
      - rubocop:
        requires:
          - validate

jobs:
  validate:
    docker:
      - image: ruby:2.3.1
    steps:
      - checkout
      - run: bundle install
      - run: rake validate
  lint:
    docker:
      - image: ruby:2.2.6
    steps:
      - checkout
      - run: bundle install
      - run: rake lint
  rubocop:
    docker:
      - image: ruby:2.2.6
    steps:
      - checkout
      - run: bundle install
      - run: rubocop
  
